global:
  imagePullSecrets:
  - application-collection

specs:
  image:
    registry: dp.apps.rancher.io
    repository: containers/ollama
    tag: 0.6.2
    pullPolicy: IfNotPresent

ingress:
  enabled: false
service:
  nodePort: 31434
  type: NodePort
persistentVolume:
  storageClass: local-path

ollama: 
  # -- List of models to pull at container startup
  models:
    pull:
      - qwen2.5:0.5b-instruct
    create:
      - name: suse-k8s-bot
        template: |
          FROM: qwen2.5:0.5b-instruct
          TEMPLATE: |
          """{{- /*

            ------ MESSAGE PARSING ------

            */}}
            {{- /*
            Declare the prompt structure variables to be filled in from messages
            */}}
            {{- $system := "" }}
            {{- $documents := "" }}
            {{- $documentCounter := 0 }}
            {{- $thinking := true }}
            {{- $citations := false }}
            {{- $hallucinations := false }}
            {{- $length := "" }}
            {{- $originality := "" }}

            {{- /*
            Loop over messages and look for a user-provided system message and documents
            */ -}}
            {{- range .Messages }}

                {{- /* User defined system prompt(s) */}}
                {{- if (eq .Role "system")}}
                    {{- if (ne $system "") }}
                        {{- $system = print $system "\n\n" }}
                    {{- end}}
                    {{- $system = print $system .Content }}
                {{- end}}

                {{- /*
                NOTE: Since Ollama collates consecutive roles, for control and documents, we
                    work around this by allowing the role to contain a qualifier after the
                    role string.
                */ -}}

                {{- /* Role specified controls */ -}}
                {{- if (and (ge (len .Role) 7) (eq (slice .Role 0 7) "control")) }}
                    {{- if (eq .Content "thinking")}}{{- $thinking = true }}{{- end}}
                    {{- if (eq .Content "citations")}}{{- $citations = true }}{{- end}}
                    {{- if (eq .Content "hallucinations")}}{{- $hallucinations = true }}{{- end}}
                    {{- if (and (ge (len .Content) 7) (eq (slice .Content 0 7) "length "))}}
                        {{- $length = slice .Content 7 }}
                    {{- end}}
                    {{- if (and (ge (len .Content) 12) (eq (slice .Content 0 12) "originality "))}}
                        {{- $originality = slice .Content 12 }}
                    {{- end}}
                {{- end}}

                {{- /* Role specified document */ -}}
                {{- if (and (ge (len .Role) 8) (eq (slice .Role 0 8) "document")) }}
                    {{- if (ne $documentCounter 0)}}
                        {{- $documents = print $documents "\n\n"}}
                    {{- end}}
                    {{- $identifier := ""}}
                    {{- if (ge (len .Role) 9) }}
                        {{- $identifier = (slice .Role 9)}}
                    {{- end}}
                    {{- if (eq $identifier "") }}
                        {{- $identifier := print $documentCounter}}
                    {{- end}}
                    {{- $documents = print $documents "<|start_of_role|>document {\"document_id\": \"" $identifier "\"}<|end_of_role|>\n" .Content "<|end_of_text|>"}}
                    {{- $documentCounter = len (printf "a%*s" $documentCounter "")}}
                {{- end}}
            {{- end}}

            {{- /*
            If no user message provided, build the default system message
            */ -}}
            {{- if eq $system "" }}
                {{- $system = "Knowledge Cutoff Date: April 2024.\nYou are SUSE AI customized model from Granite, Granite developed by IBM but SUSE-KAI developed by SUSE."}}

                {{- /* Add Tools prompt */}}
                {{- if .Tools }}
                    {{- $system = print $system " You are a helpful assistant with access to the following tools. When a tool is required to answer the user's query, respond only with <|tool_call|> followed by a JSON list of tools used. If a tool does not exist in the provided list of tools, notify the user that you do not have the ability to fulfill the request." }}
                {{- end}}

                {{- /* Add documents prompt */}}
                {{- if $documents }}
                    {{- if .Tools }}
                        {{- $system = print $system "\n"}}
                    {{- else }}
                        {{- $system = print $system " "}}
                    {{- end}}
                    {{- $system = print $system "Write the response to the user's input by strictly aligning with the facts in the provided documents. If the information needed to answer the question is not available in the documents, inform the user that the question cannot be answered based on the available data." }}
                    {{- if $citations}}
                        {{- $system = print $system "\nUse the symbols <|start_of_cite|> and <|end_of_cite|> to indicate when a fact comes from a document in the search result, e.g <|start_of_cite|> {document_id: 1}my fact <|end_of_cite|> for a fact from document 1. Afterwards, list all the citations with their corresponding documents in an ordered list."}}
                    {{- end}}
                    {{- if $hallucinations}}
                        {{- $system = print $system "\nFinally, after the response is written, include a numbered list of sentences from the response with a corresponding risk value that are hallucinated and not based in the documents."}}
                    {{- end}}
                {{- end}}

                {{- /* Prompt without tools or documents */}}
                {{- if (and (not .Tools) (not $documents)) }}
                    {{- $system = print $system " You are a helpful AI assistant."}}
                    {{- if $thinking}}
                        {{- $system = print $system "\nRespond to every user query in a comprehensive and detailed way. You can write down your thoughts and reasoning process before responding. In the thought process, engage in a comprehensive cycle of analysis, summarization, exploration, reassessment, reflection, backtracing, and iteration to develop well-considered thinking process. In the response section, based on various attempts, explorations, and reflections from the thoughts section, systematically present the final solution that you deem correct. The response should summarize the thought process. Write your thoughts between <think></think> and write your response between <response></response> for each user query."}}
                    {{- end}}
                {{- end}}

            {{- end}}
            {{- /*

            ------ TEMPLATE EXPANSION ------

            */}}
            {{- /* System Prompt */ -}}
            <|start_of_role|>system<|end_of_role|>{{- $system }}<|end_of_text|>

            {{- /* Tools */ -}}
            {{- if .Tools }}
            <|start_of_role|>available_tools<|end_of_role|>[
            {{- range $index, $_ := .Tools }}{"name": "{{ .Function.Name }}", "arguments": {{ .Function.Arguments }}}
            {{ . }}
            {{- if and (ne (len (slice $.Tools $index)) 1) (gt (len $.Tools) 1) }},
            {{- end}}
            {{- end }}
            ]<|end_of_text|>
            {{- end}}

            {{- /* Documents */ -}}
            {{- if $documents }}
            {{ $documents }}
            {{- end}}

            {{- /* Standard Messages */}}
            {{- range $index, $_ := .Messages }}
            {{- if (and
                (ne .Role "system")
                (or (lt (len .Role) 7) (ne (slice .Role 0 7) "control"))
                (or (lt (len .Role) 8) (ne (slice .Role 0 8) "document"))
            )}}
            <|start_of_role|>
            {{- if eq .Role "tool" }}tool_response
            {{- else }}{{ .Role }}
            {{- end }}<|end_of_role|>
            {{- if .Content }}{{ .Content }}
            {{- else if .ToolCalls }}<|tool_call|>
            {{- range .ToolCalls }}{"name": "{{ .Function.Name }}", "arguments": {{ .Function.Arguments }}}
            {{- end }}
            {{- end }}
            {{- if eq (len (slice $.Messages $index)) 1 }}
            {{- if eq .Role "assistant" }}
            {{- else }}<|end_of_text|>
            <|start_of_role|>assistant
            {{- if and (ne $length "") (ne $originality "") }} {"length": "{{ $length }}", "originality": "{{ $originality }}"}
            {{- else if ne $length "" }} {"length": "{{ $length }}"}
            {{- else if ne $originality "" }} {"originality": "{{ $originality }}"}
            {{- end }}<|end_of_role|>
            {{- end -}}
            {{- else }}<|end_of_text|>
            {{- end }}
            {{- end }}
            {{- end }}"""



   
