global:
  imagePullSecrets:
  - application-collection
image:
  registry: dp.apps.rancher.io
  repository: containers/open-webui
  tag: 0.6.9
ollamaUrls:
- http://suseai-suse-ai-mcp-ollama.suseai.svc.cluster.local:11434
persistence:
  storageClass: local-path
ollama:
  enabled: false
pipelines:
  enabled: True
  persistence:
    enabled: false
    storageClass: local-path
tika:
  enabled: True
ingress:
  enabled: true
  class: ""
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: ollama
  tls: true
service:
  type: LoadBalancer
  annotations: {}
  port: 8088
  targetPort: 80
  nodePort: 31000
  labels: {}
  loadBalancerClass: ""
# -- OpenAI base API URL to use. Defaults to the Pipelines service endpoint when Pipelines are enabled, and "https://api.openai.com/v1" if Pipelines are not enabled and this value is blank
openaiBaseApiUrl: ""
# -- Env vars added to the Open WebUI deployment. Most up-to-date environment variables can be found here: https://docs.openwebui.com/getting-started/env-configuration/

extraEnvVars:
  # -- Default API key value for Pipelines. Should be updated in a production deployment, or be changed to the required API key if not using Pipelines
- name: ENV
  value: "dev"
- name: OPENAI_API_KEY
  value: "0p3n-w3bu!"
- name: DEFAULT_MODELS
  value: ""
- name: DEFAULT_USER_ROLE
  value: "user"
- name: WEBUI_NAME
  value: "SUSE AI"
- name: GLOBAL_LOG_LEVEL
  value: INFO
- name: ENABLE_DIRECT_CONNECTIONS
  value: "True"
# - name: TOOL_SERVER_CONNECTIONS
#   value: |
#       [{
#         "url": "http://mcpo-service.suseai.svc.cluster.local:8000/toolbox",
#         "path": "openapi.json",
#         "auth_type": "bearer",
#         "key": "top-secret",
#         "config": {
#           "enable": true,
#           "access_control": {
#             "read": {
#               "group_ids": [],
#               "user_ids": []
#             },
#             "write": {
#               "group_ids": [],
#               "user_ids": []
#             }
#           }
#         }
#       }]







